version: 1.0.{build}

image:
  - Visual Studio 2022
  - Ubuntu2004

platform:
  - x64

environment:
  matrix:
    - nodejs_version: "20"
    - nodejs_version: "18"
    - nodejs_version: "16"
    - nodejs_version: "14"
#
# matrix:
#   exclude:
#    - image: Visual Studio 2022
#      nodejs_version: 18
#    - image: Visual Studio 2022
#      nodejs_version: 20

test_script:
  - ps: Write-Host "jspf-cserver test script"

for:
-
    matrix:
      only:
        - image: Visual Studio 2022
  
    clone_folder: c:\projects\jspf-cserver
    install:
      - cmd: powershell Install-Product node $env:nodejs_version
      - cmd: node --version
      - cmd: npm --version

    build_script:
      - cmd: cd c:\projects\jspf-cserver
      - cmd: node --version
      - ps: Get-Command npm
      - cmd: npm install
      - cmd: npm run init
      - cmd: node_modules\.bin\tsc --version
      - cmd: node_modules\.bin\tsc

    test_script:
      - cmd: npm run app
-        
    matrix:
      only:
        - image: Ubuntu2004
        - platform: x64
    clone_folder: /home/appveyor/projects/jspf-cserver
    
    install:
      - nvm install $nodejs_version
      - npm install

    build_script:
      - sh: node --version
      - sh: cd /home/appveyor/projects/jspf-cserver
      - sh: ./node_modules/.bin/tsc --version
      - sh: ./node_modules/.bin/tsc
      - sh: npm run circular
      - sh: npm run init

    test_script:
      - sh: npm run app

